### ISSUE TITLE
peerDeps issues

### ISSUE THREAD

**Issue by dantman** [Quernest/mui-modal-provider#28]
peerDeps is currently:
```json
  "peerDependencies": {
    "@types/react": "^16.8.6",
    "react": "^16.8.0",
    "react-dom": "^16.8.0"
  },
```

The react deps should probably be updated to handle React 17+.

Also `@types/react` is probably not necessary as a peer dep.

**Comment by Quernest** [comment]
> 
> 
> peerDeps is currently:
> 
> ```json
>   "peerDependencies": {
>     "@types/react": "^16.8.6",
>     "react": "^16.8.0",
>     "react-dom": "^16.8.0"
>   },
> ```
> 
> The react deps should probably be updated to handle React 17+.
> 
> Also `@types/react` is probably not necessary as a peer dep.

I think it's better to leave `@types/react` as a peer dependency to avoid possible compiler errors / warnings.

You can also check the same way organized in the material-ui core.
https://github.com/mui-org/material-ui/blob/bb7b028fdee25b08f24f22dbfd09f31797c98363/packages/material-ui/package.json#L42
