### ISSUE TITLE
Don't auto hide modal

### ISSUE THREAD

**Issue by sm2017** [Quernest/mui-modal-provider#3]
Here https://github.com/Quernest/mui-modal-provider/blob/master/src/ModalProvider.tsx#L87 we call `hideModal(id);` , it called when user touched backdrop

I want to prevent auto hide on backdrop click , user cannot close modal anyway!

**Comment by Quernest** [comment]
> Here https://github.com/Quernest/mui-modal-provider/blob/master/src/ModalProvider.tsx#L87 we call `hideModal(id);` , it called when user touched backdrop
> 
> I want to prevent auto hide on backdrop click , user cannot close modal anyway!

For material-ui you can disable it using `disableBackdropClick: true` flag

```js
    const modal = showModal(HelloWorldDialog, {
      title: 'Hello World',
      description: 'description text',
      disableBackdropClick: true, // <---------
      onConfirm: () => modal.hide(),
      onCancel: () => modal.hide(),
    });
```
