### ISSUE TITLE
"Cannot read property 'props' of undefined" error if component unmounts before onClose is called

### ISSUE THREAD

**Issue by dantman** [Quernest/mui-modal-provider#35]
If the component hosting useMount was unmounted for some reason before the onClose is called the ModalProvider will fail with an error. This will of course also bypass most error boundaries due to how high up ModalProvider normally would be.

This is because DESTROY_BY_ROOT_ID runs and then HIDE runs and the state is missing the id in payload.id.

https://codesandbox.io/s/vigorous-benz-ign4q?file=/src/App.js

This can happen in real apps if a modal does async things as part of its confirm button. e.g. A confirm dialog's confirm button makes an API call, then on success emits a snackbar and closes the dialog. If that API call had side effects (react-query, GraphQL libraries) that happens to change the app to a state where the component that happens to be hosting useModal no longer exists.

**Comment by Quernest** [comment]
> 
> 
> If the component hosting useMount was unmounted for some reason before the onClose is called the ModalProvider will fail with an error. This will of course also bypass most error boundaries due to how high up ModalProvider normally would be.
> 
> This is because DESTROY_BY_ROOT_ID runs and then HIDE runs and the state is missing the id in payload.id.
> 
> https://codesandbox.io/s/vigorous-benz-ign4q?file=/src/App.js
> 
> This can happen in real apps if a modal does async things as part of its confirm button. e.g. A confirm dialog's confirm button makes an API call, then on success emits a snackbar and closes the dialog. If that API call had side effects (react-query, GraphQL libraries) that happens to change the app to a state where the component that happens to be hosting useModal no longer exists.

Thank you for the comment! I will check this in more detail later. For now you can use `disableAutoDestroy = true` option for `useModal` hook. 

```js
useModal({ disableAutoDestroy: true });
```
