### ISSUE TITLE
MUI Dialog API changed

### ISSUE THREAD

**Issue by dantman** [Quernest/mui-modal-provider#41]
Material UI v4.12.0 and v5 have changed the Dialog API from taking `onExited` to instead taking a `TransitionProps` object with `onExited` in it.

**Comment by dantman** [comment]
Perhaps a good solution would be making the `onExited` handling something that can be controlled by the provider. Then you can override the current version to work with MUIv5. And a future release could switch the default to MUIv5 but still allow overriding for compatibility with MUIv4. And it'll make it work with other dialog systems too.

**Comment by Quernest** [comment]
> 
> 
> Perhaps a good solution would be making the `onExited` handling something that can be controlled by the provider. Then you can override the current version to work with MUIv5. And a future release could switch the default to MUIv5 but still allow overriding for compatibility with MUIv4. And it'll make it work with other dialog systems too.

Yes, thanks, I will do it when I have free time :)
