### ISSUE TITLE
modals aren't auto destroyed on a component unmount

### ISSUE THREAD

**Issue by Quernest** [Quernest/mui-modal-provider#5]
@Quernest maybe we can add wrapper function for showModal function in the useModal hook. This wrapper will track modal ids which were created in some component. And in useModal hook we will use useEffect to find out when component which created some modals is destroyed. And when it is destroyed we can use destroyModal to close modals created by this component?

Because if we do not close modals manually when browser back button it is pressed and some component which created modals is destroyed we can have different issues.

_Originally posted by @pavelspichonak in https://github.com/Quernest/mui-modal-provider/issues/4#issuecomment-751287469_

**Comment by pavelspichonak** [comment]
@Quernest I'd like to thank you. I've not checked how it works now but you have added this feature so fast. Thanks a lot!
And I'd like to say that I like and enjoy your code.

I'm not sure if it is good to ask it here but I hope you do not mind:

1) Using latest 4 version of material-ui with latest version of typescript I have modal window types like this:

`
import { ReactNode } from 'react';
import { DialogProps } from '@material-ui/core/Dialog';

export interface IProps extends DialogProps {}

`

and I get typescript errors:
<img width="614" alt="Screen Shot 2020-12-27 at 2 33 25 AM" src="https://user-images.githubusercontent.com/47976677/103161078-f220f700-47ed-11eb-817e-7440218cf5ba.png">

and I have to update types like this:
```

import { ReactNode } from 'react';
import { DialogProps } from '@material-ui/core/Dialog';

export interface IProps extends DialogProps {
  onClose: (() => void);
  onExited: () => void;
}
```

Is it your package typings issue or not?

2) now I can pass any props to `showModal` method.
Is it possible to update typings to be able to pass only that props which passed modal component supports?

For example if I use showModal like this:

`showModal(Modal, modalPropsObject);`

I'd like to be able to pass only that props which Modal component declared in its typings for typescript?

P.S. I see you are from Ukraine. Maybe it possible somehow to contact you? I'm from Belarus and if you do not mind it would be great to discuss these questions if you have time. Thanks a lot.

**Comment by Quernest** [comment]
> 
> 
> @Quernest I'd like to thank you. I've not checked how it works now but you have added this feature so fast. Thanks a lot!
> And I'd like to say that I like and enjoy your code.
> 
> I'm not sure if it is good to ask it here but I hope you do not mind:
> 
>     1. Using latest 4 version of material-ui with latest version of typescript I have modal window types like this:
> 
> 
> ```
> 
> import { ReactNode } from 'react';
> import { DialogProps } from '@material-ui/core/Dialog';
> 
> export interface IProps extends DialogProps {}
> ```
> 
> and I get typescript errors:
> <img alt="Screen Shot 2020-12-27 at 2 33 25 AM" width="614" src="https://user-images.githubusercontent.com/47976677/103161267-2f868400-47f0-11eb-8758-c28f648f9faa.png">
> 
> and I have to update types like this:
> 
> ```
> 
> import { ReactNode } from 'react';
> import { DialogProps } from '@material-ui/core/Dialog';
> 
> export interface IProps extends DialogProps {
>   onClose: () => void;
>   onExited: () => void;
> }
> ```
> 
> Is it your package typings issue or not?
> 
>     1. now I can pass any props to `showModal` method.
>        Is it possible to update typings to be able to pass only that props which passed modal component supports?
> 
> 
> For example if I use showModal like this:
> 
> `showModal(Modal, modalPropsObject);`
> 
> I'd like to be able to pass only that props which Modal component declared in its typings for typescript?
> 
> P.S. I see you are from Ukraine. Maybe it is possible somehow to contact you? I'm from Belarus and if you do not mind it would be great to discuss these questions if you have time. Thanks a lot.

Thank you for your comment. I am glad that this package is useful to you 🙂

You have this error because the `DialogProps`  don't have the same types as the `IProps` fields in the library. Especially `onClose` and `onExited` fields conflicts with it.

```js
interface IProps {
  // ...
  onClose?: () => void;
  onExited?: () => void;
  // ...
}
```

To fix this issue, I will remove this fields from the `IProps` interface and you can extend the `DialogProps`.

But remember that the `open` prop **is required** for the `DialogProps` interface and optional for `IProps`. If you are going to use the `DialogProps` interface this prop will have to be passed in the initial props in `showModal` or `updateModal` / `modal.update` to avoid errors / warnings from typescript. But in any case this property will be set automatically when `showModal` is called.

Regarding the strict typing of props for a component - I think it might be possible to use Generics. I will create a ticket for a future update.

**Comment by pavelspichonak** [comment]
@Quernest thanks a lot!
