### ISSUE TITLE
Support with React 18

### ISSUE THREAD

**Issue by samislam** [Quernest/mui-modal-provider#64]
Will mui-modal-provider support react 18? 

![Loading...](https://i.ibb.co/2578QdS/Screenshot-from-2022-08-04-21-17-15.png)

**Comment by Quernest** [comment]
> Will mui-modal-provider support react 18?
> 
> ![Loading...](https://camo.githubusercontent.com/ceb72fa49ef1bf0d5fb2d0fd1417b879b2b588defd8c30ac096f1328e17805c4/68747470733a2f2f692e6962622e636f2f323537385164532f53637265656e73686f742d66726f6d2d323032322d30382d30342d32312d31372d31352e706e67)

Sure, I will make an update soon
