### ISSUE TITLE
Rendering a lazy-loaded dialog?

### ISSUE THREAD

**Issue by takanuva15** [Quernest/mui-modal-provider#72]
Hi, I tried setting up a lazy-loaded dialog that optionally renders based on what the user selects. 

```reactjs
const LazyLoadedDialog = React.lazy(() => import('./MyDialog');

...

showModal(LazyLoadedDialog);
```

Unfortunately, this doesn't seem to work since showModal is expecting the dialog to be an immediately available component. Is there a way to adjust the showModal function to show lazy-loaded dialogs to help boost app performance?

(Btw, this is a really awesome npm library! I use it at work to make managing modals super easy)

**Comment by Quernest** [comment]
Hey @takanuva15, thanks for your feedback 😊 I just published a new version that supports the Suspense API. You can try it

**Comment by takanuva15** [comment]
Wow, that was fast - wasn't expecting a response for a month lol. Seems to work fine in my app so I give it a thumbs up.

Thanks for that amazingly quick turnaround!
