### ISSUE TITLE
Do not destroy modal on component unmount

### ISSUE THREAD

**Issue by takanuva15** [Quernest/mui-modal-provider#75]
Hi, I'm dealing with a situation where I have a dropdown menu which shows a list of options. When the user clicks on an option, it triggers the modal which displays a message, does some background work, and auto-closes. However, when the user clicks the dropdown option, this hides the dropdown menu and automatically unmounts the dropdown option's component. Unfortunately, this is also causing the modal to disappear (a bit surprisingly) even though the modal is rendered at the root of the DOM tree instead of within the component and thus there should be no impact on modal visibility.

I read #5 posted in 2020 and it looks like this behavior was set up on purpose to handle scenarios where the user clicks the browser back button. In my case, I am not worried about the browser back button since the modal auto-closes. Is it possible for us to add a flag option to the `showModal` command so that it will not destroy the modal on component unmount if the flag is set to `true`?

(I can not move up the code for showing the modal out of the option component into the dropdown component because that would break the SRP principle. I also have a bunch of options for the user to select to do different things and show various modals, so moving all that code into the dropdown component would cause its code size to grow unreasonably large)

---

As an aside, thanks again for making this great package - I've used it probably 10 times now in various places in my app.

**Comment by Quernest** [comment]
> Hi, I'm dealing with a situation where I have a dropdown menu which shows a list of options. When the user clicks on an option, it triggers the modal which displays a message, does some background work, and auto-closes. However, when the user clicks the dropdown option, this hides the dropdown menu and automatically unmounts the dropdown option's component. Unfortunately, this is also causing the modal to disappear (a bit surprisingly) even though the modal is rendered at the root of the DOM tree instead of within the component and thus there should be no impact on modal visibility.
> 
> I read #5 posted in 2020 and it looks like this behavior was set up on purpose to handle scenarios where the user clicks the browser back button. In my case, I am not worried about the browser back button since the modal auto-closes. Is it possible for us to add a flag option to the `showModal` command so that it will not destroy the modal on component unmount if the flag is set to `true`?
> 
> (I can not move up the code for showing the modal out of the option component into the dropdown component because that would break the SRP principle. I also have a bunch of options for the user to select to do different things and show various modals, so moving all that code into the dropdown component would cause its code size to grow unreasonably large)
> 
> As an aside, thanks again for making this great package - I've used it probably 10 times now in various places in my app.

Hi! Could you please provide an example? I tested the following dropdown list and it works fine

```tsx
const currencies = [
  {
    value: 'USD',
    label: '$',
  },
  {
    value: 'EUR',
    label: '€',
  },
  {
    value: 'BTC',
    label: '฿',
  },
  {
    value: 'JPY',
    label: '¥',
  },
];

<TextField
  id="outlined-select-currency"
  select
  label="Select"
  defaultValue="EUR"
  helperText="Please select your currency"
>
  {currencies.map((option) => (
    <MenuItem key={option.value} value={option.value} onClick={() => showModal(SimpleDialog)}>
      {option.label}
    </MenuItem>
  ))}
</TextField>
```

**Comment by takanuva15** [comment]
Hey sorry, guess I should have been clearer that I'm actually using a recursive submenu built using MUI and the MUI Popper. I made a demo sandbox with a sample MUI recursive submenu that you can view here: https://codesandbox.io/p/sandbox/gh-75-mui-recursive-submenu-demo-modal-destroyed-xe8y9v

After you click "view files" and load the list, selecting any of the options for an individual file (eg "Option1" or "Option2") will print a log line to the console, but the modal doesn't show since the option component itself is destroyed soon afterwards. 

I also added a "dummy default" which works normally since it's part of the dropdown list which is not destroyed after clicking

**Comment by Quernest** [comment]
> Hey sorry, guess I should have been clearer that I'm actually using a recursive submenu built using MUI and the MUI Popper. I made a demo sandbox with a sample MUI recursive submenu that you can view here: https://codesandbox.io/p/sandbox/gh-75-mui-recursive-submenu-demo-modal-destroyed-xe8y9v
> 
> After you click "view files" and load the list, selecting any of the options for an individual file (eg "Option1" or "Option2") will print a log line to the console, but the modal doesn't show since the option component itself is destroyed soon afterwards.
> 
> I also added a "dummy default" which works normally since it's part of the dropdown list which is not destroyed after clicking

Thanks 🙂 

You pointed out the previous issue correctly but here it's the other way round where you want to keep the Dialog open even if the component that called it is unmounted.

Have you tried using the `useModal` hook with this setting?

```tsx
export function DropdownOption1() {
  const { showModal } = useModal({ disableAutoDestroy: true });
  
  const runExtraCodeAndShowDialog = async () => {
    console.log("Executing1...");
    const { hide } = showModal(SimpleDialog, { title: "Doing Action1" });
    await new Promise((resolve) => setTimeout(resolve, 2000)); //replace with other important task
    hide();
    console.log("Done Executing1.");
  };

  return <MenuItem onClick={runExtraCodeAndShowDialog}>Option1</MenuItem>;
}
```

The `disableAutoDestroy` not just for the back button. It is for all cases where a component that uses the `useModal` hook has been unmounted before closing the dialog

**Comment by takanuva15** [comment]
Shoot I didn't realize that was an option lol. I tested it out and it works. Is there a doc page for what options we have for showModal?

**Comment by Quernest** [comment]
> Shoot I didn't realize that was an option lol. I tested it out and it works. Is there a doc page for what options we have for showModal?

There's a little part in the README. I want to do but I can't bring myself 😅
